name: SkStuff
author: TheBukor
description: A Skript addon which adds extra functionalities such as NBT and extended WorldEdit support.
version: 1.4.2.1
main: me.TheBukor.SkStuff.SkStuff
softdepend: [Skript, WorldEdit]