name: SkStuff
author: TheBukor
description: A Skript addon which adds extra functionalities such as NBT and extended WorldEdit support.
version: 1.2.2
main: me.TheBukor.SkStuff
softdepend: [Skript]